import { NextResponse } from "next/server";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import * as XLSX from "xlsx";

export async function GET(req: Request) {
  const session = await getServerSession(authOptions);
  if (session?.user?.role !== "ADMIN") {
    return NextResponse.json({ error: "Unauthorized" }, { status: 403 });
  }

  const { searchParams } = new URL(req.url);
  const month = parseInt(searchParams.get("month") || String(new Date().getMonth() + 1));
  const year = parseInt(searchParams.get("year") || String(new Date().getFullYear()));

  try {
    const records = await prisma.record.findMany({
      where: { month, year },
      include: { user: { select: { name: true, username: true } } }
    });

    // Format timestamp nicely
    const generatedAt = new Date().toLocaleString("id-ID", {
      dateStyle: "full", timeStyle: "long"
    });
    const generatedBy = session.user?.name || session.user?.email || "Administrator";
    
    // 1. Create Header (AOA)
    const headerInfo = [
      ["FCMM SYSTEM - OPERATIONAL AUDIT REPORT"],
      [""],
      ["Report Period", `${month}/${year}`],
      ["Generated By", generatedBy],
      ["Generated Date", generatedAt],
      [""] // Empty row before data table
    ];

    const exportData = records.map((r: any, idx: number) => {
      // Calculate usages
      const w1Usage = (r.week1 != null && r.initial != null) ? r.week1 - r.initial : null;
      const w2Usage = (r.week2 != null && r.week1 != null) ? r.week2 - r.week1 : null;
      const w3Usage = (r.week3 != null && r.week2 != null) ? r.week3 - r.week2 : null;
      const w4Usage = (r.week4 != null && r.week3 != null) ? r.week4 - r.week3 : null;
      const w5Usage = (r.week5 != null && r.week4 != null) ? r.week5 - r.week4 : null;
      
      let lastVal = null;
      if (r.week5 != null) lastVal = r.week5;
      else if (r.week4 != null) lastVal = r.week4;
      else if (r.week3 != null) lastVal = r.week3;
      else if (r.week2 != null) lastVal = r.week2;
      else if (r.week1 != null) lastVal = r.week1;

      const totalUsage = (lastVal != null && r.initial != null) ? lastVal - r.initial : 0;

      return {
        "No": idx + 1,
        "User / Department": r.user.name || r.user.username,
        "Category": r.category,
        "Color Mode": r.colorMode,
        "Initial Meter": r.initial,
        "W1 Meter": r.week1,
        "W1 Usage": w1Usage,
        "W2 Meter": r.week2,
        "W2 Usage": w2Usage,
        "W3 Meter": r.week3,
        "W3 Usage": w3Usage,
        "W4 Meter": r.week4,
        "W4 Usage": w4Usage,
        "W5 Meter": r.week5,
        "W5 Usage": w5Usage,
        "Total Usage": totalUsage,
      };
    });

    const worksheet = XLSX.utils.aoa_to_sheet(headerInfo);
    XLSX.utils.sheet_add_json(worksheet, exportData, { origin: "A7" });

    // Set auto-width
    const colWidths = [
      { wch: 5 },  // No
      { wch: 30 }, // User
      { wch: 15 }, // Category
      { wch: 15 }, // Color Mode
      { wch: 15 }, // Initial
      { wch: 12 }, // W1
      { wch: 12 }, // W1 Usage
      { wch: 12 }, // W2
      { wch: 12 }, // W2 Usage
      { wch: 12 }, // W3
      { wch: 12 }, // W3 Usage
      { wch: 12 }, // W4
      { wch: 12 }, // W4 Usage
      { wch: 12 }, // W5
      { wch: 12 }, // W5 Usage
      { wch: 15 }, // Total
    ];
    worksheet["!cols"] = colWidths;

    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, "Usage Report");

    const buf = XLSX.write(workbook, { type: "buffer", bookType: "xlsx" });

    const response = new NextResponse(buf, {
      status: 200,
      headers: {
        "Content-Disposition": `attachment; filename="FCMM_Report_${year}_${month}.xlsx"`,
        "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      },
    });
    
    // Explicitly free memory for low-RAM VPS
    exportData.length = 0;
    records.length = 0;

    return response;
  } catch (error) {
    console.error(error);
    return NextResponse.json({ error: "Failed to generate report" }, { status: 500 });
  }
}
